deadwater88/legislate-me

- frontend/components/LoginForm.js
- frontend/components/app.js
- frontend/components/common/Button.js
- frontend/components/common/Card.js
- frontend/components/common/CardSection.js
- frontend/components/common/Input.js
- frontend/components/common/index.js
Add app entry file called app.js in Components directory, add common components directory to components folder, this holds commonly used components. Add LoginForm component to Components directory.
> Add app entry, common components folder, and LoginForm Component

- frontend/components/LoginForm.js
- frontend/components/LoginFormContainer.js
Add Toggle functionality to LoginForm to toggle in between sign up and login. Create LoginFormContainer to map dispatch to LoginForm.
> Login form container

- frontend/components/LoginFormContainer.js
Add ErrorAction for SessionsReducer  to LoginFormContainer
> Add correct error action to LoginFormContainer

- frontend/components/user-profile/UserContainer.js
add UserContainer, User and UserSettings
> add UserContainer

- frontend/components/common/index.js
- frontend/components/user-profile/UserSettings.js
Go to index.js in common to see what each reusable component does.
> Add documentation to common components and start UserSettings component

- frontend/components/CustomizeInterestList/CustomizeInterestListContainer.js
- frontend/components/app.js
- frontend/components/login/LoginForm.js
- frontend/components/root.js
- frontend/reducers/subjects_reducer.js
- index.android.js
- index.ios.js
Pointed Android and iOS entry files to Root component instead of App. Wrapped Root in Provider so that all child components can have access to store.
> Styled login

- frontend/util/host_util.js
- frontend/util/session_api_util.js
- frontend/util/subject_api_util.js
- frontend/util/user_api_util.js
Created HOST_URL variable in util file, and interpolated it into all ajax calls.
> Add ajax env

- frontend/components/bill_view/BillViewContainer.js
Create Bill AJAX calls, and BillViewContainer and BillView
> Create BillViewContainer and BillView

- frontend/actions/bill_actions.js
- frontend/actions/bookmark_actions.js
- frontend/components/bill_index/bill_index.js
- frontend/components/bill_index/bill_index_container.js
- frontend/components/bill_index/bill_index_item.js
- frontend/components/login/login_navigator.js
- frontend/reducers/bill_reducer.js
- frontend/reducers/bookmarks_reducer.js
- frontend/reducers/root_reducer.js
- frontend/util/bill_api_util.js
- frontend/util/bookmark_api_util.js
Build out bill index and bookmarked bills redux cycle. Pretty bare bones right now and without testing as we're waiting on API buildout but most of structure there.
> Bill index

- frontend/components/app.js
- frontend/components/login/login_navigator.js
> Correct filepaths

- frontend/components/bill_index/bill_index.js
- frontend/components/bill_index/bill_index_item.js
- frontend/components/common/navbar/router.js
Is this what you were envisioning? Need to incorporate an event listener that bubbles up--but nested Stack navigator inside of Home Tab Nav?
> Refactor home TabNav to have nested StackNav

- frontend/components/bill_view/contact_representatives_view.js
Add Communications library to BillView
> add Communications to BillView

- frontend/components/app.js
- frontend/components/app_container.js
- frontend/components/common/navbar/router.js
- frontend/components/root.js
If the user is logged in, render the home page. Otherwise, render the splash page.
> Conditional splash page

- frontend/components/bill_view/bill_view.js
- frontend/components/bill_view/contact_representatives_view.js
- frontend/components/bill_view/sponsor_bill_view.js
- frontend/components/user_profile/RepresentativesView.js
Add Styles to BillView and completely refactor communications functions into RepresentativesView. Also, created SponsorBillView to show Bill Sponsor
> Style bill view

- frontend/components/subjects/subject.js
- frontend/components/subjects/subject_container.js
- frontend/util/bill_api_util.js
- frontend/util/subject_api_util.js
Finish Subject Container and Subject, the Subject is dependent on BillView. We should probably get that working.
> Create subject container and subject

- frontend/actions/bill_actions.js
- frontend/components/CustomizeInterestList/CustomizeInterestList.js
- frontend/components/CustomizeInterestList/CustomizeInterestListContainer.js
- frontend/components/bill_index/bill_index.js
- frontend/components/bill_index/bill_index_container.js
- frontend/components/common/navbar/router.js
- frontend/components/subjects/subject_container.js
- frontend/components/subjects/subjects_index.js
- frontend/components/user_profile/user_profile.js
- frontend/components/user_profile/user_profile_navigator.js
- frontend/util/bill_api_util.js
Implement correct navigation from user profile to its various components, as well as main home screen to discover tab.
> Fix navigation

- webSplash/css/responsive.css
- webSplash/index.html
- webSplash/style.css
> Write splash copy

- frontend/util/user_api_util.js
Make correct AJAX calls from user_api_util by adding "s" to "user".
> Make users plural in user_api_util

- frontend/components/common/Input.js
- frontend/components/user_profile/RepresentativesView.js
- frontend/components/user_profile/UserSettings.js
> Style user settings

- frontend/actions/subject_actions.js
- frontend/components/CustomizeInterestList/CustomizeInterestListContainer.js
- frontend/util/subject_api_util.js
Remove fetchSubjects API call.
Remove error callback that logs the error.
> Remove unnecessary fetchSubjects

- frontend/reducers/representatives_reducer.js
- frontend/util/user_api_util.js
Refactor representativesReducer to populate representatives state on sign in.
> Refactor representatives view

- frontend/components/bill_index/bill_index_item.js
> render pictures

- frontend/components/bill_index/bill_index.js
- frontend/components/bill_index/bill_index_item.js
- frontend/components/bill_view/bill_view.js
- frontend/components/bookmarked_bills/bookmarked_bills.js
- frontend/util/user_api_util.js
> Fix bill index props

- frontend/components/login/submit_address/submit_address.js
Add new local state to submit_address and new form
> Refactor submit address

- frontend/components/bill_index/bill_index.js
- frontend/components/bill_index/bill_index_item.js
Pass the correct navigation props through to bill view.
> Fix navigation from bill index item to bill view

- frontend/components/bill_index/bill_index.js
- frontend/components/bill_view/bill_view.js
- frontend/components/bill_view/bill_view_container.js
- frontend/components/login/submit_address/submit_address.js
- frontend/components/user_profile/RepresentativesView.js
- frontend/reducers/bookmarks_reducer.js
- frontend/reducers/session_reducer.js
> Add reps to bill view

- frontend/components/bill_index/bill_index.js
- frontend/components/bill_index/bill_index_item.js
- frontend/components/common/navbar/router.js
- frontend/components/user_profile/RepresentativesView.js
> Style bill index

- backend/legislate_me/settings.py
- backend/users/views.py
- frontend/components/login/LoginForm.js
- frontend/util/host_util.js
Implement Errors to render by toast and Backend User Setup Logic.
> Android Toast Errors and Handle Backup Setup Logic

- frontend/components/subjects/subjects_index.js
Position subject overlay text differently
> Change positioning of subject text

- frontend/components/subjects/subjects_index.js
- frontend/util/bill_api_util.js
Overlay opaque subject images over black background to increase text contrast
> StyleSubjects

- frontend/components/user_profile/user_profile.js
- frontend/components/user_profile/user_profile_navigator.js
Change the user profile background to a gradient.
Center and enlarge the text appropriately. 
Change color scheme of buttons and text.
> Style user profile

- frontend/components/login/Splash.js
reduce font-size from 34 to 30 and add more text to splash.
> reduce font-size from 34 to 30

- frontend/actions/bill_actions.js
- frontend/actions/session_actions.js
- frontend/components/CustomizeInterestList/CustomizeInterestList.js
- frontend/components/CustomizeInterestList/CustomizeInterestListItem.js
- frontend/components/app.js
- frontend/components/bill_index/bill_index.js
- frontend/components/bill_index/bill_index_item.js
- frontend/components/bill_view/contact_representatives_view.js
- frontend/components/bookmarked_bills/bookmarked_bills.js
- frontend/components/common/Button.js
- frontend/components/user_profile/UserSettings.js
Removed almost all of the console.log statements in the app. I left three, all of which were in the oauth components. I would check them out and see if they are important.
> remove console.log statements from app
